project:
  type: website
  output-dir: docs


website:
  title: "Cosmic Trajectories"
  navbar:
    logo: Logos/ct_logo.png
    logo-alt: "Cosmic Trajectories"
    left:
      - text: "Trajecta"
        href: Trajecta.qmd
      - text: "Market News & Events"
        href: MarketNews.qmd
      - text: "Trajecta Insights"
        menu:
          - text: "Founder's Blog" 
            href: FounderBlog.qmd
      - text: "Misc."
        menu:
          - text: "About"
            href: AboutPage.qmd
          - text: "Contact"
            href: ContactPage.qmd


format:
  html:
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    favicon: Logos/ct_logo.png
    include-after-body: _footer.html
    
editor: visual